---
- hosts: nodes
  become: true
  vars:
    cni_version: v0.8.3
    crictl_version: v1.16.1
    kube_version: v1.16.3
    authorized_key_url: https://github.com/slashdevsda.keys
  roles:
    - common
    - k8s-node
