---
# file: roles/common/tasks/main.yml
- name: Install package curl from repo
  pacman:
    name: curl
    state: present
  
- name: Create k8s user
  user:
    name: k8s
    state: present

- name: Create /opt/bin directory
  file:
    path: /opt/bin
    state: directory
    mode: '0755'

- name: Create /opt/cni/bin directory
  file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'

- name: Create /opt/k8s-ansible directory
  file:
    path: /opt/k8s-ansible
    state: directory
    mode: '0755'
    

# CNI
- name: Download cni tgz
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/{{ cni_version }}/cni-plugins-linux-arm-{{ cni_version }}.tgz
    dest: /opt/k8s-ansible/cni-plugins-linux-arm-{{ cni_version }}.tgz


- name: Extract cni tgz
  unarchive: src=/opt/k8s-ansible/cni-plugins-linux-arm-{{ cni_version }}.tgz
             dest=/opt/cni/bin
             copy=no

- name: make /opt/cni/bin/ content exec
  file:
    path: /opt/cni/bin/
    mode: '0750'
    recurse: yes

# CRICTL

- name: Download critcl tgz
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-arm.tar.gz
    dest: /opt/k8s-ansible/crictl-{{ crictl_version }}-arm.tar.gz



- name: Extract crictl tgz
  unarchive:
    src: /opt/k8s-ansible/crictl-{{ crictl_version }}-arm.tar.gz
    dest: /opt/bin
    copy: no
    mode: 0750

# - name: make /opt/cni/bin/ content exec
#   file:
#     path: /opt/cni/bin/
#     mode: '0750'
#     recurse: yes
