---
# file: roles/common/tasks/main.yml
- name: Install package curl from repo
  pacman:
    name: curl
    state: present
  
- name: Create k8s user
  user:
    name: k8s
    state: present

- name: Set authorized keys to k8s user
  authorized_key:
    user: k8s
    state: present
    key: "{{ authorized_key_url }}"

- name: Add user "k8s" to sudoers
  lineinfile:
    path: /etc/sudoers.d/k8s
    line: 'k8s ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
